server:
  port: 8000
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.83.147:3306/plutus
#    url: jdbc:mysql://127.0.0.1:3306/plutus
    username: root
    password: 980721Club4
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 180000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      continue-on-error: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名和下划线命名的自动转换